package study

import "time"

// Candidate is a content item found during discovery.
// Over-inclusive by design — ranking filters false positives.
type Candidate struct {
	ID       string   `json:"id"`
	Source   string   `json:"source"`   // "text", "index", "lsp", "memory", "file"
	Location Location `json:"location"`
	Preview  string   `json:"preview"`
	SizeHint int      `json:"size_hint"`
}

// Location identifies where a candidate lives in its source.
type Location struct {
	Path      string `json:"path"`
	StartLine int    `json:"start_line"`
	EndLine   int    `json:"end_line"`
	Symbol    string `json:"symbol"`
}

// ExtractedItem is content pulled for a candidate at a specific granularity.
type ExtractedItem struct {
	ID          string       `json:"id"`
	Content     string       `json:"content"`
	Granularity string       `json:"granularity"` // "signature", "interface", "declaration", "block", "file_summary"
	TokenCount  int          `json:"token_count"`
	Metadata    ItemMetadata `json:"metadata"`
}

// ItemMetadata describes the extracted content's provenance.
type ItemMetadata struct {
	Language string    `json:"language"`
	Path     string    `json:"path"`
	Lines    [2]int    `json:"lines"`
	Symbol   string    `json:"symbol"`
	Kind     string    `json:"kind"` // "function", "type", "interface", "method", "const", "var", "block", "file"
	Distance int       `json:"distance"`
	Modified time.Time `json:"modified"`
}

// RankedItem pairs an extracted item with its composite relevance score.
type RankedItem struct {
	ExtractedItem
	Score float64 `json:"score"`
}

// StudyOutput is the structured content in the output envelope.
type StudyOutput struct {
	Summary     string         `json:"summary"`
	Items       []OutputItem   `json:"items"`
	AISummaries []AISummary    `json:"ai_summaries"`
	Metadata    OutputMetadata `json:"metadata"`
}

// OutputItem is a single item in the study output, ordered by relevance.
type OutputItem struct {
	Path        string `json:"path"`
	Symbol      string `json:"symbol"`
	Kind        string `json:"kind"`
	Granularity string `json:"granularity"`
	Distance    int    `json:"distance"`
	Tokens      int    `json:"tokens"`
	Content     string `json:"content"`
}

// AISummary is a dense summary generated by Tier 3 compression.
type AISummary struct {
	Theme   string   `json:"theme"`
	Covers  []string `json:"covers"`
	Tokens  int      `json:"tokens"`
	Content string   `json:"content"`
}

// OutputMetadata provides runtime and quality information about the study invocation.
type OutputMetadata struct {
	Source         string         `json:"source"`
	Entry          string         `json:"entry"`
	Role           string         `json:"role"`
	Depth          string         `json:"depth"`
	TokenEstimated bool           `json:"token_estimated"`
	Coverage       Coverage       `json:"coverage"`
	Discovery      DiscoveryStats `json:"discovery"`
	Timing         Timing         `json:"timing"`
}

// Coverage tracks how much relevant content fit within the budget.
type Coverage struct {
	IncludedItems     int     `json:"included_items"`
	ExcludedItems     int     `json:"excluded_items"`
	IncludedScoreMass float64 `json:"included_score_mass"`
	CompressionTier   int     `json:"compression_tier_used"`
	BudgetUsed        int     `json:"budget_used"`
	BudgetTotal       int     `json:"budget_total"`
	AISummaries       int     `json:"ai_summaries"`
}

// DiscoveryStats records how many candidates each discovery method found.
type DiscoveryStats struct {
	TextCandidates    int `json:"text_candidates"`
	IndexCandidates   int `json:"index_candidates"`
	LSPCandidates     int `json:"lsp_candidates"`
	WebCandidates     int `json:"web_candidates"`
	DeduplicatedTotal int `json:"deduplicated_total"`
}

// Timing records how long each stage took in milliseconds.
type Timing struct {
	DiscoverMs int64 `json:"discover_ms"`
	ExtractMs  int64 `json:"extract_ms"`
	RankMs     int64 `json:"rank_ms"`
	CompressMs int64 `json:"compress_ms"`
}

// Granularity levels for extraction, from most to least detail.
const (
	GranDeclaration = "declaration"
	GranInterface   = "interface"
	GranSignature   = "signature"
	GranBlock       = "block"
	GranFileSummary = "file_summary"
)

// Item kind constants.
const (
	KindFunction  = "function"
	KindType      = "type"
	KindInterface = "interface"
	KindMethod    = "method"
	KindConst     = "const"
	KindVar       = "var"
	KindBlock     = "block"
	KindFile      = "file"
)

// Compression tier constants.
const (
	TierNone       = 0
	TierDemotion   = 1
	TierElision    = 2
	TierAI         = 3
)

// maxCompressionTier returns the maximum tier allowed by the compression flag.
func maxCompressionTier(compression string) int {
	switch compression {
	case "none":
		return TierNone
	case "structural":
		return TierElision
	case "ai":
		return TierAI
	default:
		return TierAI
	}
}
